/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jazzros_ffmpegtest_RendererWrapper */

#ifndef _Included_com_jazzros_ffmpegtest_RendererWrapper
#define _Included_com_jazzros_ffmpegtest_RendererWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jazzros_ffmpegtest_RendererWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jazzros_ffmpegtest_RendererWrapper_on_1surface_1created
  (JNIEnv *, jobject);

/*
 * Class:     com_jazzros_ffmpegtest_RendererWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_jazzros_ffmpegtest_RendererWrapper_on_1surface_1changed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jazzros_ffmpegtest_RendererWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jazzros_ffmpegtest_RendererWrapper_on_1draw_1frame
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_jazzros_ffmpegtest_FFMpegAV_nativeInit  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
